[project]
name = "fpsim"
version = "0.1.0"
description = "Cycle-accurate simulation / measurement of floating-point assembly routines"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pulp"]
