name: Integration tests

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: X86
            runner: ubuntu-latest
            core: CL
          - name: A64
            runner: macos-13
            core: P
    runs-on: ${{ matrix.runner }}
    name: "Integration tests (${{ matrix.core }})"
    steps:
      - uses: actions/checkout@master
      - name: Install the latest version of uv and activate the environment
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
      - run: uv sync
      - run: uv run python3 main.py --core ${{ matrix.core }} ts at1 at3 ddadd madd fpan333
